SELECT DISTINCT *
 FROM (
         SELECT U.NOM_USUARIO || ' ' || U.SBN_USUARIO NOME,
                U.NUM_DOCUMENTO,
                U.IDF_TIPO_DOCUMENTO,
                CU.DSC_EMAIL
         FROM USUARIO U, COMPLEMENTO_USUARIO CU, DBA_USERS DB
         WHERE (
                  (U.NOM_USUARIO || ' ' || U.SBN_USUARIO LIKE 'DANIEL ANSELMO' || '%') OR
                  (U.NOM_USUARIO || ' ' || U.SBN_USUARIO LIKE '%' || 'DANIEL ANSELMO' || '%') OR
                  (FNC_TIRA_ACENTOS(U.NOM_USUARIO || ' ' || U.SBN_USUARIO) LIKE UPPER(FNC_TIRA_ACENTOS('%DANIEL%'))) OR
                  (FNC_TIRA_ACENTOS(U.NOM_USUARIO || ' ' || U.SBN_USUARIO) LIKE UPPER(FNC_TIRA_ACENTOS('%ANSELMO%')))
                )
        AND U.NUM_USER_BANCO = CU.NUM_USER_BANCO(+)
        AND U.NUM_DOCUMENTO IS NOT NULL
        AND (CU.IDF_EXCLUSIVO_FORPONTO IS NULL OR CU.IDF_EXCLUSIVO_FORPONTO = 'N')
        AND U.NOM_USUARIO_BANCO = DB.USERNAME
        AND DB.ACCOUNT_STATUS = 'OPEN'
       )
WHERE ROWNUM <= 10
ORDER BY NOME
