/*Histórico Ordem Serviço*/

SELECT  TO_CHAR(B.DTA_HOR_HISTORICO,'DD/MM/YYYY HH24:MI:SS') DTA_HOR_HISTORICO, 
D.DSC_MOTIVO, C.DSC_SITUACAO_OS,

        A.NUM_ORDEM, E.NOM_UNIDADE_EXECUTANTE, B.DTA_HOR_HISTORICO DTA_HISTORICO,

        (F.NOM_USUARIO||CHR(32)||F.SBN_USUARIO) NOM_USUARIO, B.COD_SITUACAO_OS, 
E.COD_UNIDADE_EXECUTANTE,

        A.NUM_ORDEM_ORIGEM, B.SEQ_HISTORICO_OS

FROM HISTORICO_ORDEM_SERVICO B, ORDEM_SERVICO A,

     TIPO_SITUACAO_OS C, MOTIVO_CANCELAMENTO_OS D, UNIDADE_EXECUTANTE E,

     USUARIO F

WHERE A.NUM_ORDEM_SERVICO = 43

  AND A.ANO_ORDEM_SERVICO = 2019

  AND A.NUM_ORDEM = B.NUM_ORDEM

  AND B.COD_SITUACAO_OS = C.COD_SITUACAO_OS

  AND B.COD_NUM_MOTIVO = D.COD_MOTIVO_CANCELAMENTO(+)

  AND B.COD_UNIDADE_EXECUTANTE = E.COD_UNIDADE_EXECUTANTE

  AND B.NUM_USER_LOG = F.NUM_USER_BANCO

ORDER BY B.DTA_HOR_HISTORICO DESC;--, B.DTA_HOR_HISTORICO DESC
-----------------------------------------------
SELECT * FROM ordem_servico os
WHERE os.num_ordem_servico = 84156
AND os.ano_ordem_servico = 2018;
