--Incorporação Patrimônio
-----------------------------------------------
SELECT DISTINCT A.SEQ_NOTA_FISCAL, A.COD_FORNECEDOR, B.NOM_FORNECEDOR,

  A.VLR_NOTA_FISCAL, A.NUM_NOTA_FISCAL,

  TO_CHAR(A.DTA_RECEBIMENTO,'DD/MM/YYYY') DTA_RECEBIMENTO, D.DSC_TIPO_AQUISICAO,

  ( SELECT COUNT(*) FROM ITEM_NOTA_FISCAL X, INCORPORACAO Y

     WHERE X.SEQ_NOTA_FISCAL = C.SEQ_NOTA_FISCAL AND

           X.COD_MATERIAL = C.COD_MATERIAL AND

           X.SEQ_NOTA_FISCAL = Y.SEQ_NOTA_FISCAL(+) AND

           X.COD_MATERIAL = Y.COD_MATERIAL(+) AND

           X.QTD_ENTREGUE <> Y.QTD_INCORPORADA

  ) QTD_RECEB_PARCIAL

FROM NOTA_FISCAL A, FORNECEDOR B, ITEM_NOTA_FISCAL C,TIPO_AQUISICAO D

WHERE (A.SEQ_NOTA_FISCAL=C.SEQ_NOTA_FISCAL)

  AND (A.COD_FORNECEDOR=B.COD_FORNECEDOR)

  AND (C.COD_TIPO_AQUISICAO=D.COD_TIPO_AQUISICAO)

  AND (C.DTA_HOR_ESTOQUE <> TO_DATE('01/01/1800','DD/MM/YYYY'))

  AND (C.IDF_MAT_PERMANENTE = 1 )

  AND (C.IDF_STATUS<2)

  AND (A.IDF_OPERACAO=1)

  AND EXISTS(SELECT DISTINCT VIC.COD_INSTITUICAO FROM V_INSTITUICAO_COMPRAS VIC

             WHERE VIC.COD_INST_SIST_CC = 1

               AND VIC.COD_INSTITUICAO = A.COD_INSTITUICAO)
  AND A.NUM_NOTA_FISCAL = 16694 

ORDER BY NOM_FORNECEDOR, NUM_NOTA_FISCAL;
----------------------------------------------

SELECT * FROM nota_fiscal nf
WHERE nf.num_nota_fiscal = 16694
AND nf.seq_nota_fiscal = 713379;

select * from ESTOQUE.ITEM_NOTA_FISCAL t
where t.seq_nota_fiscal = 713379
FOR UPDATE;
