--70103501 Febre amarela, e 70102752 
SELECT *
 FROM material m
 WHERE m.cod_material IN ('70103501', '70102752');
 
 SELECT *
  FROM estoque_pronto_uso epu
  WHERE epu.cod_material IN ('70103501', '70102752');
  
  select * 
             from ESTOQUE.item_requisicao_material t
  WHERE t.cod_material = '70103501';
where t.num_requisicao = :m_num_requisicao
and   t.ano_requisicao_material = :m_ano_requisicao_material;
  
  SELECT RM.NUM_REQUISICAO,
         RM.ANO_REQUISICAO_MATERIAL,
         RM.IDF_SOLICITANTE,
         (SELECT U_SOL.NOM_USUARIO||' '||U_SOL.SBN_USUARIO FROM USUARIO U_SOL
         WHERE U_SOL.NUM_USER_BANCO = RM.IDF_SOLICITANTE) USR_SOLICITANTE,
         RM.COD_CENCUSTO_SOLICITANTE,
         RM.DTA_REQUISICAO,
         CASE RM.IDF_TIPO_REQUISICAO
            WHEN 0 THEN 'Entrega'
            WHEN 1 THEN 'Devolução'
            WHEN 2 THEN 'Transferência'
         END TIPO_REQUISICAO,
         (SELECT CC_SOL.NOM_CENCUSTO
          FROM CENTRO_CUSTO CC_SOL WHERE CC_SOL.COD_CENCUSTO = RM.COD_CENCUSTO_SOLICITANTE) CENCUSTO_SOLICITANTE,         
         RM.COD_CENCUSTO_ATENDENTE,
         (SELECT CC_ATE.NOM_CENCUSTO
          FROM CENTRO_CUSTO CC_ATE WHERE CC_ATE.COD_CENCUSTO = RM.COD_CENCUSTO_ATENDENTE) CENCUSTO_ATENDENTE,       
         RM.IDF_ATENDENTE,
         (SELECT U_ATE.NOM_USUARIO||' '||U_ATE.SBN_USUARIO FROM USUARIO U_ATE
         WHERE U_ATE.NUM_USER_BANCO = RM.IDF_ATENDENTE) USR_ATENDENTE,        
         RM.DTA_ATENDIMENTO,
         IRM.COD_MATERIAL,
         IRM.QTD_REQUISI_DEVOLVIDA,
         IRM.QTD_FORNE_RECEBIDA
    FROM REQUISICAO_MATERIAL RM
    JOIN ITEM_REQUISICAO_MATERIAL IRM
      ON IRM.NUM_REQUISICAO = RM.NUM_REQUISICAO
     AND IRM.ANO_REQUISICAO_MATERIAL = RM.ANO_REQUISICAO_MATERIAL     
   WHERE RM.COD_CENCUSTO_SOLICITANTE IN
         ('CACD02010', 'CACD02046', 'CACN01037', 'CACD02022')
     AND IRM.COD_MATERIAL = '70102752'--'70103501'
     AND RM.DTA_REQUISICAO >= TO_DATE('01/01/2020', 'DD/MM/YYYY')
     ORDER BY RM.DTA_REQUISICAO DESC;
     
     SELECT *
      FROM REQUISICAO_MATERIAL RM
      WHERE RM.NUM_REQUISICAO = 1565827
      AND RM.ANO_REQUISICAO_MATERIAL = 2020;
